workflows:
  android-app:
    name: Android App Build
    max_build_duration: 60
    environment:
      java: 11
      vars:
        PACKAGE_NAME: "com.aaryan7.dastakmobile"
    scripts:
      - name: Set up local properties
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Set up Gradle wrapper
        script: |
          gradle wrapper
          chmod +x ./gradlew
      - name: Build debug APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
